name: Unit Test
description: Perform unit tests

inputs:
  name:
    description: Name of the distribution
    required: true
  arch:
    description: Architecture of the distribution
    required: true
  build-type:
    description: The type of build to perform
    required: false
    default: Release

runs:
  using: composite
  steps:
    - name: Set tweak
      id: version
      run: |
        # Set the tweak version (YYMMDD + 2 digit run attempt)
        now=$(date +'%Y%m%d')
        number=$(printf '%02d' ${{ github.run_attempt }})
        tweak="$(date +'%Y%m%d')$(printf '%02d' ${{ github.run_attempt }})"

        echo date: $now
        echo number: $number
        echo tweak: $tweak

        echo tweak=$tweak >> $GITHUB_OUTPUT

    - name: Generate build
      shell: bash
      run: |
        mkdir build && cd build
        cmake ../src -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} -DTWEAK_VERSION=${{ steps.version.outputs.tweak }} -Duse_prov_client=ON -Dhsm_type_symm_key=ON -DCOMPILE_WITH_STRICTNESS=ON -DBUILD_TESTS=OFF -DBUILD_MODULETEST=ON -DBUILD_SAMPLES=OFF -Duse_default_uuid=ON -DBUILD_ADAPTERS=ON

    - name: Build azure-osconfig
      shell: bash
      run: cmake --build ./build --config ${{ inputs.build-type }} --parallel

    - name: Run ctest
      shell: bash
      run: cd build && ctest --verbose > ../${{ inputs.name }}-${{ inputs.arch }}.log

    - name: Generate test report
      uses: ./.github/actions/gtest-xml
      if: success() || failure()
      with:
        path: ./build/gtest-output
        output: ${{ inputs.name }}-${{ inputs.arch }}.xml

    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: unit-test
        path: |
          ${{ inputs.name }}-${{ inputs.arch }}.log
          ${{ inputs.name }}-${{ inputs.arch }}.xml