instance of OsConfigResource as $OsConfigResource0ref
{
    ResourceID = "Ensure that permissions on /etc/ssh/sshd_config are configured";
    RuleId = "43119747-263c-2c92-4ce5-726e63259049";
    PayloadKey = "EnsurePermissionsOnEtcSshSshdConfig";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsurePermissionsOnEtcSshSshdConfig";
    ReportedObjectName = "auditEnsurePermissionsOnEtcSshSshdConfig";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsurePermissionsOnEtcSshSshdConfig";
    DesiredObjectValue = "600";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource1ref
{
    ResourceID = "Ensure that the SSH protocol is configured";
    RuleId = "35868e8c-97eb-4981-ab79-99b25101cc86";
    PayloadKey = "EnsureSshBestPracticeProtocol";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureSshBestPracticeProtocol";
    ReportedObjectName = "auditEnsureSshBestPracticeProtocol";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshBestPracticeProtocol";
    DesiredObjectValue = "2";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource2ref
{
    ResourceID = "Ensure that the SSH IgnoreRhosts is configured";
    RuleId = "43945588-1bdc-495c-bac8-6a71a62d30aa";
    PayloadKey = "EnsureSshBestPracticeIgnoreRhosts";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureSshBestPracticeIgnoreRhosts";
    ReportedObjectName = "auditEnsureSshBestPracticeIgnoreRhosts";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshBestPracticeIgnoreRhosts";
    DesiredObjectValue = "yes";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource3ref
{
    ResourceID = "Ensure that the SSH LogLevel is configured";
    RuleId = "31f1a912-1b98-42fd-8381-1e8d1033bfd1";
    PayloadKey = "EnsureSshLogLevelIsSet";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureSshLogLevelIsSet";
    ReportedObjectName = "auditEnsureSshLogLevelIsSet";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshLogLevelIsSet";
    DesiredObjectValue = "INFO";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource4ref
{
    ResourceID = "Ensure that the SSH MaxAuthTries is configured";
    RuleId = "e7708534-5d98-406f-83ae-1de835b2906e";
    PayloadKey = "EnsureSshMaxAuthTriesIsSet";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureSshMaxAuthTriesIsSet";
    ReportedObjectName = "auditEnsureSshMaxAuthTriesIsSet";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshMaxAuthTriesIsSet";
    DesiredObjectValue = "6";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource5ref
{
    ResourceID = "Ensure that the allowed users for SSH access are configured";
    RuleId = "dc8da71d-aeba-4c03-8835-36fe158e372a";
    PayloadKey = "EnsureAllowUsersIsConfigured";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureAllowUsersIsConfigured";
    ReportedObjectName = "auditEnsureAllowUsersIsConfigured";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureAllowUsersIsConfigured";
    DesiredObjectValue = "*@*";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource6ref
{
    ResourceID = "Ensure that the denied users for SSH are configured";
    RuleId = "1db7d147-3a75-4637-8cdc-c119e22d0206";
    PayloadKey = "EnsureDenyUsersIsConfigured";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureDenyUsersIsConfigured";
    ReportedObjectName = "auditEnsureDenyUsersIsConfigured";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureDenyUsersIsConfigured";
    DesiredObjectValue = "root";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource7ref
{
    ResourceID = "Ensure that the allowed groups for SSH are configured";
    RuleId = "d9868b1f-0c8e-4adb-889e-14e374874ece";
    PayloadKey = "EnsureAllowGroupsIsConfigured";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureAllowGroupsIsConfigured";
    ReportedObjectName = "auditEnsureAllowGroupsIsConfigured";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureAllowGroupsIsConfigured";
    DesiredObjectValue = "*";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource8ref
{
    ResourceID = "Ensure that the denied groups for SSH are configured";
    RuleId = "f85c04a4-427b-4ee1-b988-c3ff7b4998cc";
    PayloadKey = "EnsureDenyGroupsConfigured";
    ComponentName = "SecurityBaseline";
    ExpectedObjectValue = "PASS";
    InitObjectName = "initEnsureDenyGroupsConfigured";
    ReportedObjectName = "auditEnsureDenyGroupsConfigured";
    DesiredObjectName = "remediateEnsureDenyGroupsConfigured";
    DesiredObjectValue = "root";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource9ref
{
    ResourceID = "Ensure that the SSH HostBasedAuthentication is configured";
    RuleId = "66511f6b-f690-43df-9654-642260699eec";
    PayloadKey = "EnsureSshHostbasedAuthenticationIsDisabled";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureSshHostbasedAuthenticationIsDisabled";
    ReportedObjectName = "auditEnsureSshHostbasedAuthenticationIsDisabled";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshHostbasedAuthenticationIsDisabled";
    DesiredObjectValue = "no";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource10ref
{
    ResourceID = "Ensure that the SSH PermitRootLogin is configured";
    RuleId = "16511f6b-f690-43df-9654-642260699eec";
    PayloadKey = "EnsureSshPermitRootLoginIsDisabled";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureSshPermitRootLoginIsDisabled";
    ReportedObjectName = "auditEnsureSshPermitRootLoginIsDisabled";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshPermitRootLoginIsDisabled";
    DesiredObjectValue = "no";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource11ref
{
    ResourceID = "Ensure that the SSH PermitEmptyPasswords is configured";
    RuleId = "d50c3f39-264c-4cdc-b0ba-89de8a0f6828";
    PayloadKey = "EnsureSshPermitEmptyPasswordsIsDisabled";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureSshPermitEmptyPasswordsIsDisabled";
    ReportedObjectName = "auditEnsureSshPermitEmptyPasswordsIsDisabled";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshPermitEmptyPasswordsIsDisabled";
    DesiredObjectValue = "no";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource12ref
{
    ResourceID = "Ensure that the SSH ClientAliveCountMax is configured";
    RuleId = "fd9f1554-6b72-8610-826e-78578e6f7811";
    PayloadKey = "EnsureSshClientIntervalCountMaxIsConfigured";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureSshClientIntervalCountMaxIsConfigured";
    ReportedObjectName = "auditEnsureSshClientIntervalCountMaxIsConfigured";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshClientIntervalCountMaxIsConfigured";
    DesiredObjectValue = "0";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource13ref
{
    ResourceID = "Ensure that the SSH ClientAliveInterval is configured";
    RuleId = "c848bba4-93b1-4756-b08a-ff94c2b4814c";
    PayloadKey = "EnsureSshClientAliveIntervalIsConfigured";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureSshClientAliveIntervalIsConfigured";
    ReportedObjectName = "auditEnsureSshClientAliveIntervalIsConfigured";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshClientAliveIntervalIsConfigured";
    DesiredObjectValue = "3600";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource14ref
{
    ResourceID = "Ensure that the SSH LoginGraceTime is configured";
    RuleId = "39aa5c2b-5b36-84a7-4022-570a53c86ff9";
    PayloadKey = "EnsureSshLoginGraceTimeIsSet";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureSshLoginGraceTimeIsSet";
    ReportedObjectName = "auditEnsureSshLoginGraceTimeIsSet";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshLoginGraceTimeIsSet";
    DesiredObjectValue = "60";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource15ref
{
    ResourceID = "Ensure that only approved MAC algorithms are used";
    RuleId = "483e8b0c-7572-8467-7e0c-26e1e9ce6359";
    PayloadKey = "EnsureOnlyApprovedMacAlgorithmsAreUsed";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureOnlyApprovedMacAlgorithmsAreUsed";
    ReportedObjectName = "auditEnsureOnlyApprovedMacAlgorithmsAreUsed";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureOnlyApprovedMacAlgorithmsAreUsed";
    DesiredObjectValue = "hmac-sha2-256,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-512-etm@openssh.com";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource16ref
{
    ResourceID = "Ensure that the SSH warning banner is configured";
    RuleId = "9e240540-5e0a-4b60-beb2-57421c65a0b9";
    PayloadKey = "EnsureSshWarningBannerIsEnabled";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureSshWarningBannerIsEnabled";
    ReportedObjectName = "auditEnsureSshWarningBannerIsEnabled";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshWarningBannerIsEnabled";
    DesiredObjectValue = "#######################################################################\n\nAuthorized access only!\n\nIf you are not authorized to access or use this system, disconnect now!\n\n#######################################################################\n";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource17ref
{
    ResourceID = "Ensure that the SSH PermitUserEnvironment is configured";
    RuleId = "0e665978-91f4-45af-bb7b-e4090b600c8d";
    PayloadKey = "EnsureUsersCannotSetSshEnvironmentOptions";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureUsersCannotSetSshEnvironmentOptions";
    ReportedObjectName = "auditEnsureUsersCannotSetSshEnvironmentOptions";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureUsersCannotSetSshEnvironmentOptions";
    DesiredObjectValue = "no";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource18ref
{
    ResourceID = "Ensure that appropriate ciphers are used for SSH";
    RuleId = "b07d4c69-a1d9-4c22-a486-634ec3b8c380";
    PayloadKey = "EnsureAppropriateCiphersForSsh";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureAppropriateCiphersForSsh";
    ReportedObjectName = "auditEnsureAppropriateCiphersForSsh";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureAppropriateCiphersForSsh";
    DesiredObjectValue = "aes128-ctr,aes192-ctr,aes256-ctr";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource19ref
{
    ResourceID = "Ensure that the SSH port is configured";
    RuleId = "1310042d-193f-414a-a7e3-b2c4e89aa537";
    PayloadKey = "EnsureSshPortIsConfigured";
    ComponentName = "SecurityBaseline";
    InitObjectName = "initEnsureSshPortIsConfigured";
    ReportedObjectName = "auditEnsureSshPortIsConfigured";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshPortIsConfigured";
    DesiredObjectValue = "22";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxSshServerSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OMI_ConfigurationDocument
{
    Version="2.0.0";
    CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
    Author="Microsoft";
    GenerationDate="10/16/2024 16:38:00 PST";
    Name="OsConfigSshServerSecurity";
};
