name: Container run
description: Run a docker container

inputs:
  image:
    description: The name of the image.
    required: true
  local:
    description: The path to a local image.
    required: false
  arch:
    description: The container architecture.
    required: false
    default: linux/amd64
  mount:
    description: The volume to mount.
    required: true
  tag:
    description: The container tag.
    required: false
    default: latest

outputs:
  id:
    description: The container id of the running container.
    value: ${{ steps.container.outputs.id }}

runs:
  using: composite
  steps:
    - name: Login to container registry
      if: ${{ !inputs.local }}
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup container
      id: container
      run: |
        if [[ -n "${{ inputs.local }}" ]]; then
          echo "Loading local image: $image"
          docker load -i ${{ inputs.local }}
        fi

        id=$(docker run -di --privileged -v ${{ inputs.mount }} --platform=${{ inputs.arch }} ${{ inputs.image }}:${{ inputs.tag }})

        echo Container ${{ inputs.image }}:${{ inputs.tag }} running: $id
        echo ::set-output name=id::$id
      shell: bash