name: Container run
description: Run a docker container

inputs:
  registry:
    description: Container registry
    required: false
    default: ghcr.io
  image:
    description: The name of the image.
    required: true
  arch:
    description: The container architecture.
    required: false
    default: linux/amd64
  mount:
    description: The volume to mount.
    required: true
  tag:
    description: The container tag.
    required: false
    default: latest

outputs:
  id:
    description: The container id of the running container.
    value: ${{ steps.container.outputs.id }}

runs:
  using: composite
  steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup container
      id: image
      run: |
        if [ -n "${{ inputs.local }}" ]; then
          echo "Loading image from ${{ inputs.local }}"
          docker load -i ${{ inputs.local }}
          echo ::set-output name=name::${{ inputs.image }}::${{ inputs.tag }}
        else
          image=${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }}
          echo "Pulling image from $image"
          docker pull $image
          echo ::set-output name=name::$image
        fi
      shell: bash

    - name: Run container
      id: container
      run: |
        echo Running container ${{ steps.image.outputs.name }}
        id=$(docker run -di --privileged -v ${{ inputs.mount }} --platform=${{ inputs.arch }} ${{ steps.image.outputs.name }})

        echo Container ID: $id
        echo ::set-output name=id::$id
      shell: bash