name: Container run
description: Run a docker container

inputs:
  registry:
    description: Container registry.
    required: false
    default: ""
  container:
    description: The name of the container.
    required: true
  mount:
    description: The volume to mount.
    required: true
  tag:
    description: The container tag.
    required: false
    default: latest
  args:
    description: Additional arguments to pass to the container.
    required: false
    default: ""

outputs:
  id:
    description: The container id of the running container.
    value: ${{ steps.container.outputs.id }}

runs:
  using: composite
  steps:
    - name: Setup container
      id: setup
      run: |
        if [ -n "${{ inputs.registry }}" ]; then
          image=${{ inputs.registry }}/${{ inputs.container }}
        else
          image=${{ inputs.container }}
        fi

        echo container=$image >> $GITHUB_OUTPUT
      shell: bash

    - name: Run container
      id: container
      shell: bash
      run: |
        name="${{ steps.setup.outputs.container }}"
        tag="${{ inputs.tag }}"
        if [[ "${tag}" =~ ^@sha256:.* ]] ; then
          container_name_tag="${name}${tag}"
          else
          container_name_tag="${name}:${tag}"
        fi
        echo "Running container ${container_name_tag}"
        id=$(docker run -di --privileged -v ${{ inputs.mount }} "${container_name_tag}")

        echo Container ID: $id
        echo id=$id >> $GITHUB_OUTPUT
