name: Container run
description: Run a docker container

inputs:
  registry:
    description: Container registry.
    required: false
    default: ""
  container:
    description: The name of the container.
    required: true
  mount:
    description: The volume to mount.
    required: true
  useQEMU:
    description: Use QEMU for emulation.
    required: false
    type: boolean
    default: false
  tag:
    description: The container tag.
    required: false
    default: latest

outputs:
  id:
    description: The container id of the running container.
    value: ${{ steps.container.outputs.id }}

runs:
  using: composite
  steps:
    - name: Setup QEMU
      if: ${{ inputs.useQEMU }}
      uses: docker/setup-qemu-action@v3

    - name: Setup container
      id: setup
      run: |
        if [ -n "${{ inputs.registry }}" ]; then
          image=${{ inputs.registry }}/${{ inputs.container }}
        else
          image=${{ inputs.container }}
        fi

        echo container=$image >> $GITHUB_OUTPUT
      shell: bash

    - name: Run container
      id: container
      run: |
        echo Running container ${{ steps.setup.outputs.container }}:${{ inputs.tag }}...
        id=$(docker run -di --privileged -v ${{ inputs.mount }} ${{ steps.setup.outputs.container }}:${{ inputs.tag }})

        echo Container ID: $id
        echo id=$id >> $GITHUB_OUTPUT
      shell: bash