version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "docker"
    directories:
      - "/devops/docker/*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      - dependency-name: "mirror/docker/library/*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "submodules"
    commit-message:
      prefix: "deps"
      include: "scope"
