name: Defer test execution
description: Wait for background services to avoid module tests races

runs:
  using: composite
  steps:
    - name: Stop apt-daily
      run: |
        source /etc/os-release
        if [[ "$ID" == "ubuntu" ]] || [[ "$ID" == "debian" ]]; then
          sudo systemctl stop apt-daily.service || true
          sudo systemctl stop apt-daily.timer || true
          sudo systemctl stop apt-daily-upgrade.service || true
          sudo systemctl stop apt-daily-upgrade.timer || true
        fi
      shell: bash

    - name: Wait for packages installed by azsec
      run: |
        source /etc/os-release
        for i in $(seq 1 60); do
          if [[ "$ID" != "ubuntu" ]] && [[ "$ID" != "debian" ]] && [[ "$ID" != "mariner" ]]; then
            break
          fi
          if [[ "$ID" == "ubuntu" ]] || [[ "$ID" == "debian" ]]; then
            if dpkg -l azsec-bpftrace 2>/dev/null | grep -q '^ii'; then
              break
            fi
          elif [[ "$ID" == "mariner" ]]; then
            if rpm -q azsec-bpftrace &>/dev/null && rpm -q KeysInUse-OpenSSL &>/dev/null; then
              break
            fi
          fi
          echo "Waiting for required packages to be installed..."
          sleep 5
        done
      shell: bash
