# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

[package]
name = "rustsample"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.0"
serde = {version = "1.0.143", features = ["derive"]}
serde_json = "1.0"
[lib]
crate-type = ["cdylib"]