# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

[package]
name = "rustsample"
version = "0.1.0"
edition = "2021"

[dependencies]
c_fixed_string = "0.2"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
