instance of OsConfigResource as $OsConfigResource0ref
{
    ResourceID = "3.1.2 Escaped Glob Version";
    PayloadKey = "/cis/azurelinux/3\\.?/v1.0.0/3/1/2/4";
    RuleId = "00000000-0000-0000-0000-000000000000";
    ComponentName = "ComplianceEngine";
    ProcedureObjectName = "procedureEscapedGlob";
    ProcedureObjectValue = "eyJhdWRpdCI6e319";
    InitObjectName = "initEscapedGlob";
    ReportedObjectName = "auditEscapedGlob";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEscapedGlob";
    DesiredObjectValue = "";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "ComplianceEngine";
    SourceInfo = "::4::5::OsConfigResource";
};
