instance of OsConfigResource as $OsConfigResource0ref
{
    ResourceID = "9.9.9 Escape Stress";
    PayloadKey = "/cis/ubuntu/22.04/v2.0.0/9/9/9";
    RuleId = "00000000-0000-0000-0000-000000000000";
    ComponentName = "ComplianceEngine";
    ProcedureObjectName = "procedureEscapeStress";
    ProcedureObjectValue = "eyJhdWRpdCI6e319";
    InitObjectName = "initEscapeStress";
    ReportedObjectName = "auditEscapeStress";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEscapeStress";
    DesiredObjectValue = "A\\B\"C\\\\D\nE\\\"F\\";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "ComplianceEngine";
    SourceInfo = "::4::5::OsConfigResource";
};
