instance of OsConfigResource as $OsConfigResource0ref
{
    ResourceID = "2.1.1 Sample With Init";
    PayloadKey = "/cis/ubuntu/22.04/v2.0.0/2/1/1";
    RuleId = "00000000-0000-0000-0000-000000000000";
    ComponentName = "ComplianceEngine";
    ProcedureObjectName = "procedureInit";
    ProcedureObjectValue = "eyJhdWRpdCI6e319";
    InitObjectName = "initInit";
    ReportedObjectName = "auditInit";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateInit";
    DesiredObjectValue = "{\"mask\":\"0600\"}";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "ComplianceEngine";
    SourceInfo = "::4::5::OsConfigResource";
};
