name: Check performance
description: Checks the performance log for failures

inputs:
  perflog:
    description: the performance log path
    required: true
  failmark:
    description: the performance failure marker
    required: true

runs:
  using: composite
  steps:
    - name: Check for performance failures
      env:
        perflog: ${{ inputs.perflog }}
        failmark: ${{ inputs.failmark }}
      run: |
        failed=false

        echo Checking $perflog
        failures=$(grep -q "$failmark" $perflog)

        if [ "$failures" != "" ]; then
            echo "Found performance failures in $perflog"
            echo "$failures"
            failed=true
        fi

        if [ "$failed" == true ]
        then
            echo "Found failures in performance log"
            exit 1
        fi
      shell: bash
