name: Check performance
description: Checks the performance log for warnings

inputs:
  perflog:
    description: the performance log path
    required: true
  mark:
    description: the performance warning marker
    required: true

runs:
  using: composite
  steps:
    - name: Check for performance warnings
      env:
        perflog: ${{ inputs.perflog }}
        mark: ${{ inputs.mark }}
      run: |
        failed=false

        echo "Checking '$perflog' for any performance warnings"
        echo "Contents of '$perflog':"
        cat "$perflog"        

        warnings=$(grep -i "$mark" $perflog || true)

        if [ -n "$warnings" ]; then
            echo "Found performance warnings in '$perflog':"
            echo "$warnings"
            failed=true
        else
            echo "Found no performance warnings in '$perflog'"
        fi

        if [ "$failed" == true ]
        then
            echo "Check performance test failed"
            exit 1
        fi
      shell: bash
