name: Check performance
description: Checks the performance log for failures

inputs:
  perflog:
    description: the performance log path
    required: true
  failmark:
    description: the performance failure marker
    required: true

runs:
  using: composite
  steps:
    - name: Check for performance failures
      env:
        perflog: ${{ inputs.perflog }}
        failmark: ${{ inputs.failmark }}
      run: |
        failed=false

        echo "Checking $perflog for any $failmark instances"
        ls -l "$perflog"
        stat "$perflog"
        echo "Contents of $perflog:"
        echo "----------\n"
        cat "$perflog"        
        echo "----------\n"

        failures=$(grep -i "$failmark" $perflog)
        echo "Failures: $failures"

        if [ -n "$failures" ]; then
            echo "Found performance failures in $perflog"
            echo "Failures: $failures"
            failed=true
        else
            echo "Found no performance failures in $perflog"
        fi

        if [ "$failed" == true ]
        then
            echo "Found failures in performance log"
            exit 1
        fi
      shell: bash
