name: Check performance
description: Checks the performance log for failures

inputs:
  perflog:
    description: the performance log path
    required: true
  failmark:
    description: the performance failure marker
    required: true

runs:
  using: composite
  steps:
    - name: Check for performance failures
      env:
        perflog: ${{ inputs.perflog }}
        failmark: ${{ inputs.failmark }}
      run: |
        perf_failure_found=false

        echo $perflog
        echo $failmark

        echo Checking $perflog
        perf_failures=$(grep -q "$failmark" $perflog)

        if [ "perf_failures" != "" ]
        then
            echo "Found performance failures in $perflog"
            echo "perf_failures"
            perf_failure_found=true
        fi

        if [ "$perf_failure_found" == true ]
        then
            echo "Found failures in performance log"
            exit 1
        fi
      shell: bash
