name: Check performance
description: Checks the performance log for failures

inputs:
  perflog:
    description: the performance log path
    required: true
  failmark:
    description: the performance failure marker
    required: true

runs:
  using: composite
  steps:
    - name: Check for performance failures
      env:
        perflog: ${{ inputs.perflog }}
        failmark: ${{ inputs.failmark }}
      run: |
        failed=false

        cat "$perflog"        

        failures=$(grep -i "$failmark" $perflog || true)

        if [ -n "$failures" ]; then
            echo "Performance failures found in $perflog:"
            echo "$failures"
            failed=true
        else
            echo "No performance failures found
        fi

        if [ "$failed" == true ]
        then
            echo "Performance failures found"
            exit 1
        fi
      shell: bash
