name: Check performance
description: Checks the performance log for failures

inputs:
  performance-log:
    description: the performance log path
    required: true
  failure-mark:
    description: the performance failure marker
    required: true

runs:
  using: composite
  steps:
    - name: Check for performance failures
      env:
        performance-log: ${{ inputs.performance-log }}
        failure-mark: ${{ inputs.failure-mark }}
      run: |
        perf_failure_found=false

        echo $performance-log
        echo $failure-mark

        echo Checking $performance-log
        perf_failures=$(grep -q "$failure-mark" $performance-log)

        if [ "perf_failures" != "" ]
        then
            echo "Found performance failures in $performance-log"
            echo "perf_failures"
            perf_failure_found=true
        fi

        if [ "$perf_failure_found" == true ]
        then
            echo "Found failures in performance log"
            exit 1
        fi
      shell: bash
