FROM mcr.microsoft.com/mirror/docker/library/ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt -y update && apt-get -y install software-properties-common
RUN apt -y update && apt-get -y install \
    build-essential \
    cmake \
    curl \
    git \
    jq \
    libgtest-dev \
    pkg-config \
    tar \
    unzip \
    wget \
    zip
