instance of LinuxOsConfigResource as $LinuxOsConfigResource0ref
{
    ResourceID = "[LinuxOsConfigResource]Ensure that the configured OSConfig policy is applied on the Linux device";
    LinuxOsConfigClassKey = "LinuxOsConfigClassKey";
    ComponentName = "";
    DesiredObjectName = "";
    DesiredObjectValue = "";
    ReportedObjectName = "";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "LinuxOsConfig";
    SourceInfo = "::4::5::LinuxOsConfigResource";
};

instance of OMI_ConfigurationDocument
{
    Version="2.0.0";
    CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
    Author="Microsoft";
    GenerationDate="2/1/2023 14:00:00";
    Name="LinuxOsConfigResource";
};
