instance of OsConfigResource as $OsConfigResource0ref
{
    ResourceID = "Ensure permissions on /etc/ssh/sshd_config are configured";
    PayloadKey = "EnsurePermissionsOnEtcSshSshdConfig";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsurePermissionsOnEtcSshSshdConfig";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsurePermissionsOnEtcSshSshdConfig";
    DesiredObjectValue = "600";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource1ref
{
    ResourceID = "Ensure SSH is configured to meet best practices (protocol 2)";
    PayloadKey = "EnsureSshBestPracticeProtocol";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureSshBestPracticeProtocol";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshBestPracticeProtocol";
    DesiredObjectValue = "2";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource2ref
{
    ResourceID = "Ensure SSH is configured to ignore rhosts";
    PayloadKey = "EnsureSshBestPracticeIgnoreRhosts";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureSshBestPracticeIgnoreRhosts";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshBestPracticeIgnoreRhosts";
    DesiredObjectValue = "yes";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource3ref
{
    ResourceID = "Ensure SSH LogLevel is set to INFO";
    PayloadKey = "EnsureSshLogLevelIsSet";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureSshLogLevelIsSet";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshLogLevelIsSet";
    DesiredObjectValue = "INFO";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource4ref
{
    ResourceID = "Ensure SSH MaxAuthTries is configured";
    PayloadKey = "EnsureSshMaxAuthTriesIsSet";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureSshMaxAuthTriesIsSet";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshMaxAuthTriesIsSet";
    DesiredObjectValue = "6";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource5ref
{
    ResourceID = "Ensure allowed users for SSH access are configured";
    PayloadKey = "EnsureAllowUsersIsConfigured";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureAllowUsersIsConfigured";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureAllowUsersIsConfigured";
    DesiredObjectValue = "*@*";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource6ref
{
    ResourceID = "Ensure denied users for SSH are configured";
    PayloadKey = "EnsureDenyUsersIsConfigured";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureDenyUsersIsConfigured";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureDenyUsersIsConfigured";
    DesiredObjectValue = "root";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource7ref
{
    ResourceID = "Ensure allowed groups for SSH are configured";
    PayloadKey = "EnsureAllowGroupsIsConfigured";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureAllowGroupsIsConfigured";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureAllowGroupsIsConfigured";
    DesiredObjectValue = "*";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource8ref
{
    ResourceID = "Ensure denied groups for SSH are configured";
    PayloadKey = "EnsureDenyGroupsConfigured";
    ComponentName = "SecurityBaseline";
    ExpectedObjectValue = "PASS";
    ReportedObjectName = "auditEnsureDenyGroupsConfigured";
    DesiredObjectName = "remediateEnsureDenyGroupsConfigured";
    DesiredObjectValue = "root";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource9ref
{
    ResourceID = "Ensure SSH host-based authenticationis disabled";
    PayloadKey = "EnsureSshHostbasedAuthenticationIsDisabled";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureSshHostbasedAuthenticationIsDisabled";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshHostbasedAuthenticationIsDisabled";
    DesiredObjectValue = "no";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource10ref
{
    ResourceID = "Ensure root login via SSH is disabled";
    PayloadKey = "EnsureSshPermitRootLoginIsDisabled";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureSshPermitRootLoginIsDisabled";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshPermitRootLoginIsDisabled";
    DesiredObjectValue = "no";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource11ref
{
    ResourceID = "Ensure that remote connection from accounts with empty passwords is disabled";
    PayloadKey = "EnsureSshPermitEmptyPasswordsIsDisabled";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureSshPermitEmptyPasswordsIsDisabled";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshPermitEmptyPasswordsIsDisabled";
    DesiredObjectValue = "no";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource12ref
{
    ResourceID = "Ensure the SSH Client Interval Count Maximum is configured";
    PayloadKey = "EnsureSshClientIntervalCountMaxIsConfigured";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureSshClientIntervalCountMaxIsConfigured";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshClientIntervalCountMaxIsConfigured";
    DesiredObjectValue = "0";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource13ref
{
    ResourceID = "Ensure the SSH Client Alive interval Interval is configured";
    PayloadKey = "EnsureSshClientAliveIntervalIsConfigured";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureSshClientAliveIntervalIsConfigured";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshClientAliveIntervalIsConfigured";
    DesiredObjectValue = "3600";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource14ref
{
    ResourceID = "Ensure the SSH LoginGraceTime is configured";
    PayloadKey = "EnsureSshLoginGraceTimeIsSet";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureSshLoginGraceTimeIsSet";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshLoginGraceTimeIsSet";
    DesiredObjectValue = "60";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource15ref
{
    ResourceID = "Ensure that only approved MAC algorithms are used";
    PayloadKey = "EnsureOnlyApprovedMacAlgorithmsAreUsed";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureOnlyApprovedMacAlgorithmsAreUsed";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureOnlyApprovedMacAlgorithmsAreUsed";
    DesiredObjectValue = "hmac-sha2-256,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-512-etm@openssh.com";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource16ref
{
    ResourceID = "Ensure the SSH warning banner is enabled";
    PayloadKey = "EnsureSshWarningBannerIsEnabled";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureSshWarningBannerIsEnabled";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureSshWarningBannerIsEnabled";
    DesiredObjectValue = "#######################################################################\n\nAuthorized access only!\n\nIf you are not authorized to access or use this system, disconnect now!\n\n#######################################################################\n";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource17ref
{
    ResourceID = "Ensure that users cannot set environment options for SSH";
    PayloadKey = "EnsureUsersCannotSetSshEnvironmentOptions";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureUsersCannotSetSshEnvironmentOptions";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureUsersCannotSetSshEnvironmentOptions";
    DesiredObjectValue = "no";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OsConfigResource as $OsConfigResource118ref
{
    ResourceID = "Ensure that appropriate ciphers are used for SSH";
    PayloadKey = "EnsureAppropriateCiphersForSsh";
    ComponentName = "SecurityBaseline";
    ReportedObjectName = "auditEnsureAppropriateCiphersForSsh";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureAppropriateCiphersForSsh";
    DesiredObjectValue = "aes128-ctr,aes192-ctr,aes256-ctr";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OsConfigSecurityBaseline";
    SourceInfo = "::4::5::OsConfigResource";
};

instance of OMI_ConfigurationDocument
{
    Version="1.0.0";
    CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
    Author="Microsoft";
    GenerationDate="11/17/2023 12:17:00 PM PST";
    Name="OsConfigSshServerSecurity";
};