#pragma include ("cim_schema_2.26.0.mof")
#pragma include ("MSFT_Qualifiers.mof")
#pragma include ("OMI_BaseResource.mof")
#pragma include ("MSFT_Credential.mof")

[ClassVersion("1.0.0")]
class OSConfig_PrototypeResource : OMI_BaseResource
{
  [key] 
  string PrototypeClassKey;

  [write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}]
  string Ensure;
  
  [read, Description ("Reported string type value" )]
  string ReportedString;

  [write, Description ("Desired string type value" )]
  string DesiredString;
  
  [read, Description ("Reported boolean type value" )]
  boolean ReportedBoolean;

  [write, Description ("Desired boolean type value" )]
  boolean DesiredBoolean;
  
  [read, Description ("Reported integer type value" )]
  boolean ReportedInteger;

  [write, Description ("Desired integer type value" )]
  uint32 DesiredInteger;

  [read, Description ("Reported status" )]
  uint32 ReportedIntegerStatus;

  [read, ValueMap{"PASS","FAIL", "ERROR", "WARNING", "SKIP"}, Values{"PASS","FAIL", "ERROR", "WARNING", "SKIP"}]
  string ReportedStringResult;

  [static, Description ("Get resource states based on input configuration document." )]
  uint32 GetTargetResource(
    [in, EmbeddedInstance ("OSConfig_PrototypeResource"), Description ("Configuration document that is to be applied.")]
    string InputResource,
    [in, Description ("Flags passed to the providers. Reserved for future use." )] 
    uint32 Flags,
    [out, EmbeddedInstance ("OSConfig_PrototypeResource"), Description ("The current state of the specified configuration resources." )]
    string OutputResource
  );
    
  [static, Description ("Test resource states based on input configuration document." )]
  uint32 TestTargetResource(
    [in, EmbeddedInstance("OSConfig_PrototypeResource"), Description ("Configuration document that to be applied." )]
    string InputResource,
    [in, Description ("Flags passed to the providers. Reserved for future use." )]
    uint32 Flags,
    [out, Description ("True if identical. False otherwise." )]
    boolean Result,
    [out, Description ("Context information that the provider can use to optimize the set, This is optional." )]
    uint64 ProviderContext
  );

  [static, Description ("Set resource states based on input configuration document." )]
  uint32 SetTargetResource(
    [in, EmbeddedInstance ("OSConfig_PrototypeResource"), Description ("Configuration document that to be applied." )]
    string InputResource,
    [in, Description ("Context information that the provider can use to optimize the set from TestTargetResource. This is optional." )]
    uint64 ProviderContext,
    [in, Description ("Flags passed to the providers. Reserved for future use." )]
    uint32 Flags
  );
};
 