instance of OSConfig_PrototypeResource as $OSConfig_PrototypeResource0ref
{
    ResourceID = "[OSConfig_PrototypeResource] Ensure the host name of the device is configured";
    PrototypeClassKey = "myKey";
    DesiredString = "GC-POC-HOST";
    DesiredInteger = 10;
    DesiredBoolean = true;
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "OSConfig";
    SourceInfo = "::4::5::OSConfig_PrototypeResource";
};

instance of OMI_ConfigurationDocument
{
    Version="2.0.0";
    CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
    Author="Microsoft";
    GenerationDate="10/19/2022 14:38:56";
    Name="OSConfig_Prototype";
};
