// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#ifndef COMPLIANCE_EVALUATOR_H
#define COMPLIANCE_EVALUATOR_H

#include "Logging.h"
#include "Result.h"

#include <map>
#include <sstream>
#include <string>

struct json_object_t;

#define AUDIT_FN(fn_name) ::compliance::Result<bool> Audit_##fn_name(std::map<std::string, std::string> args, std::ostringstream& logstream)

#define REMEDIATE_FN(fn_name) ::compliance::Result<bool> Remediate_##fn_name(std::map<std::string, std::string> args, std::ostringstream& logstream)

namespace compliance
{
using ParameterMap = std::map<std::string, std::string>;
using action_func_t = Result<bool> (*)(ParameterMap, std::ostringstream&);
using ProcedureMap = std::map<std::string, std::pair<action_func_t, action_func_t>>;
class Evaluator
{
public:
    Evaluator(const struct json_object_t* json, const ParameterMap& parameters, OsConfigLogHandle log)
        : mJson(json),
          mParameters(parameters),
          mLog(log)
    {
    }
    Evaluator(const Evaluator&) = delete;
    Evaluator(Evaluator&&) = delete;
    Evaluator& operator=(const Evaluator&) = delete;
    Evaluator& operator=(Evaluator&&) = delete;

    Result<bool> ExecuteAudit(char** payload, int* payloadSizeBytes);
    Result<bool> ExecuteRemediation();

    void setProcedureMap(ProcedureMap procedureMap);

private:
    enum class Action
    {
        Audit,
        Remediate
    };
    Result<bool> EvaluateProcedure(const struct json_object_t* json, const Action action);
    const struct json_object_t* mJson;
    const ParameterMap& mParameters;
    std::ostringstream mLogstream;
    OsConfigLogHandle mLog;
    // autogenerated, instantiated in ProcedureMap.cpp
    static ProcedureMap mProcedureMap;
    static const size_t cLogstreamMaxSize = 4096;
};
} // namespace compliance

#endif // COMPLIANCE_EVALUATOR_H
