instance of OsConfigResource as $OsConfigResource0ref
{
   ResourceID = "Ensure NIS Client is not installed";
   PayloadKey = "/cis/Ubuntu/24.04/v1.0.0/2/2/1";
   RuleId = "079122c1-4421-5be3-f897-92a1655e9228";
   ComponentName = "Compliance";
   ProcedureObjectName = "procedureObject";
   ProcedureObjectValue = "eyJuYW1lIjoiRW5zdXJlIE5JUyBDbGllbnQgaXMgbm90IGluc3RhbGxlZCIsImF1ZGl0Ijp7Im5vdCI6eyJwYWNrYWdlSW5zdGFsbGVkIjp7InBhY2thZ2VOYW1lIjoibmlzIn19fSwicGFyYW1ldGVycyI6e319";
   InitObjectName = "initObject";
   ReportedObjectName = "auditObject";
   ExpectedObjectValue = "PASS";
   DesiredObjectName = "remediateObject";
   DesiredObjectValue = "";
   ModuleName = "GuestConfiguration";
   ModuleVersion = "1.0.0";
   ConfigurationName = "ComplianceExample";
   SourceInfo = "::4::5::OsConfigResource";
};
instance of OsConfigResource as $OsConfigResource1ref
{
   ResourceID = "Ensure permissions on /etc/crontab are configured";
   PayloadKey = "/cis/Ubuntu/24.04/v1.0.0/2/4/1/2";
   RuleId = "65e74f75-0eac-58d0-1a5a-668ccb5c8f35";
   ComponentName = "Compliance";
   ProcedureObjectName = "procedureObject";
   ProcedureObjectValue = "eyJuYW1lIjoiRW5zdXJlIHBlcm1pc3Npb25zIG9uIC9ldGMvY3JvbnRhYiBhcmUgY29uZmlndXJlZCIsInJlbWVkaWF0ZSI6eyJhbnlPZiI6W3sibm90Ijp7InBhY2thZ2VJbnN0YWxsZWQiOnsicGFja2FnZU5hbWUiOiIkQ1JPTl9QS0dfTkFNRSJ9fX0seyJlbnN1cmVGaWxlUGVybWlzc2lvbnMiOnsiZmlsZW5hbWUiOiIvZXRjL2Nyb250YWIiLCJ1c2VyIjoicm9vdCIsImdyb3VwIjoicm9vdCIsInBlcm1pc3Npb25zIjoiNjAwIn19XX0sImF1ZGl0Ijp7ImFueU9mIjpbeyJub3QiOnsicGFja2FnZUluc3RhbGxlZCI6eyJwYWNrYWdlTmFtZSI6IiRDUk9OX1BLR19OQU1FIn19fSx7ImVuc3VyZUZpbGVQZXJtaXNzaW9ucyI6eyJmaWxlbmFtZSI6Ii9ldGMvY3JvbnRhYiIsInVzZXIiOiJyb290IiwiZ3JvdXAiOiJyb290IiwicGVybWlzc2lvbnMiOiI2MDAifX1dfSwicGFyYW1ldGVycyI6eyJDUk9OX1BLR19OQU1FIjoiY3JvbiJ9fQ==";
   InitObjectName = "initObject";
   ReportedObjectName = "auditObject";
   ExpectedObjectValue = "PASS";
   DesiredObjectName = "remediateObject";
   DesiredObjectValue = "CRON_PKG_NAME=cron";
   ModuleName = "GuestConfiguration";
   ModuleVersion = "1.0.0";
   ConfigurationName = "ComplianceExample";
   SourceInfo = "::4::5::OsConfigResource";
};
instance of OsConfigResource as $OsConfigResource2ref
{
   ResourceID = "Ensure permissions on /etc/cron.hourly are configured";
   PayloadKey = "/cis/Ubuntu/22.04/v2.0.0/2/4/1/3";
   RuleId = "fb59b8f0-9cf2-19bc-decc-bde4c7f49c7d";
   ComponentName = "Compliance";
   ProcedureObjectName = "procedureObject";
   ProcedureObjectValue = "eyJuYW1lIjoiRW5zdXJlIHBlcm1pc3Npb25zIG9uIC9ldGMvY3Jvbi5ob3VybHkgYXJlIGNvbmZpZ3VyZWQiLCJhdWRpdCI6eyJhbnlPZiI6W3sibm90Ijp7ImFueU9mIjpbeyJwYWNrYWdlSW5zdGFsbGVkIjp7InBhY2thZ2VOYW1lIjoiJENST05fUEtHX05BTUUifX0seyJwYWNrYWdlSW5zdGFsbGVkIjp7InBhY2thZ2VOYW1lIjoiY3JvbmllIn19XX19LHsiZW5zdXJlRmlsZVBlcm1pc3Npb25zIjp7ImZpbGVuYW1lIjoiL2V0Yy9jcm9uLmhvdXJseSIsInVzZXIiOiJyb290IiwiZ3JvdXAiOiJyb290IiwicGVybWlzc2lvbnMiOiI2MDAifX1dfSwicGFyYW1ldGVycyI6eyJDUk9OX1BLR19OQU1FIjoiY3JvbiJ9fQ==";
   InitObjectName = "initObject";
   ReportedObjectName = "auditObject";
   ExpectedObjectValue = "PASS";
   DesiredObjectName = "remediateObject";
   DesiredObjectValue = "CRON_PKG_NAME=cron";
   ModuleName = "GuestConfiguration";
   ModuleVersion = "1.0.0";
   ConfigurationName = "ComplianceExample";
   SourceInfo = "::4::5::OsConfigResource";
};
instance of OMI_ConfigurationDocument
{
    Version="3.0.0";
    CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
    Author="Microsoft";
    GenerationDate="02/26/2025 13:48:30 UTC";
    Name="ComplianceExample";
};
