// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#include <CommonUtils.h>
#include <Evaluator.h>
#include <Regex.h>
#include <StringTools.h>
#include <iostream>
#include <string>

namespace ComplianceEngine
{
namespace
{
// Audit Params - possibly we could override the generated function name
struct AuditUfwStatus2Params
{
    /// Regex that the status must match
    /// pattern:...
    regex statusRegex;

    // This stuff can easily be generated by pre-commit based on fields and comments above,
    // outside of this structure.
    static Bindings<AuditUfwStatus2Params, regex> GetBindings()
    {
        return Bindings<AuditUfwStatus2Params, regex>(&AuditUfwStatus2Params::statusRegex);
    }
};
} // anonymous namespace

AUDIT_FN2(UfwStatus2, "statusRegex:Regex that the status must match:M")
{
    UNUSED(params);
    UNUSED(indicators);
    UNUSED(context);
    std::cerr << "[" << __func__ << ":" << __LINE__ << "] " << std::endl;
    return Error("Not implemented yet");
}

// We drop the strings passed to the macro here
AUDIT_FN(UfwStatus, "statusRegex:Regex that the status must match:M")
{
    auto params = ParseArguments<AuditUfwStatus2Params>(args, GetFieldList());
    if (!params.HasValue())
    {
        return params.Error();
    }

    auto output = context.ExecuteCommand("ufw status verbose");
    if (!output.HasValue())
    {
        return indicators.NonCompliant("ufw not found: " + output.Error().message);
    }

    if (regex_search(output.Value(), params->statusRegex) == false)
    {
        return indicators.NonCompliant("Searched value not found in UFW output");
    }
    else
    {
        return indicators.Compliant("Searched value found in UFW output");
    }
}
} // namespace ComplianceEngine
