# Dotnet validate stage definition - builds/validates the dotnet sources
# Parameters:
#  - (Required) containerPath [string]: the full path to the container to be used for the build environmentr (Example. osconfig.azurecr.io/ubuntu20.04-dev-amd64:latest)
#  - (Required) sourcePath [string]: the full path to the dotnet project

parameters:
- name: containerPath
  type: string
- name: sourcePath
  type: string

stages:
- stage: dotnet_validate
  displayName: Dotnet Build Validation
  dependsOn: []

  jobs:
  - job: dotnet_validate

    pool:
      vmImage: 'ubuntu-20.04'

    steps:

    - checkout: self
      submodules: recursive
      clean: true

    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(SERVICE_CONNECTION)

    - script: |
        CONTAINER_ID=`docker run -di -v $(Build.SourcesDirectory):/AzOsConfig ${{ parameters.containerPath }} bash`
        echo CONTAINER_ID=$CONTAINER_ID
        echo "##vso[task.setvariable variable=CONTAINER_ID]$CONTAINER_ID"
      displayName: Setup Container

    - script: |
        docker exec $(CONTAINER_ID) bash -c "dotnet build /AzOsConfig/${{ parameters.sourcePath }}"
      displayName: Validate build
    