# IoTHub creation stage definition

stages:
- stage: Terraform_iothub
  displayName: Cloud - Create Hub
  pool:
        vmImage: 'ubuntu-18.04'
  jobs:
  - job: TerraformJobIotHub
    steps:
    - script: |
        sudo apt update && sudo apt install curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt install terraform
      displayName: Installing Terraform

    - script: 'terraform init'
      displayName: terraform init (IotHub)
      workingDirectory: $(Build.SourcesDirectory)/devops/terraform/iothub

    - script: 'terraform apply -var subscription_id="$(SUBSCRIPTION_ID)" -var tenant_id="$(TENANT_ID)" -var client_id="$(CLIENT_ID)" -var client_secret="$(CLIENT_SECRET)" -var key_vault_id="$(KEY_VAULT_ID)" -auto-approve'
      displayName: terraform apply
      continueOnError: true
      workingDirectory: $(Build.SourcesDirectory)/devops/terraform/iothub

    - script: |
        IOTHUB_NAME=`terraform output iothub_name`
        echo "##vso[task.setvariable variable=IOTHUB_NAME;isOutput=true]$IOTHUB_NAME"
      name: iothub_name_step
      displayName: Retreive IoTHub Name
      continueOnError: true
      workingDirectory: $(Build.SourcesDirectory)/devops/terraform/iothub

    - script: |
        IOTHUBOWNER_CONN_STR=`terraform output iothubowner_connection_string`
        echo "##vso[task.setvariable variable=IOTHUBOWNER_CONN_STR;issecret=true;isOutput=true]$IOTHUBOWNER_CONN_STR"
      name: iothubowner_conn_str_step
      displayName: Retreive iothubowner connection string
      continueOnError: true
      workingDirectory: $(Build.SourcesDirectory)/devops/terraform/iothub

    - script: |
        RESOURCE_GROUP_NAME=`terraform output resource_group_name`
        echo "##vso[task.setvariable variable=RESOURCE_GROUP_NAME;isOutput=true]$RESOURCE_GROUP_NAME"
      name: resource_group_name_step
      displayName: Retreive Resource Group Name
      continueOnError: true
      workingDirectory: $(Build.SourcesDirectory)/devops/terraform/iothub

    - script: |
        mkdir -p $(Build.ArtifactStagingDirectory)/terraform/iothub
        cp -R $(Build.SourcesDirectory)/devops/terraform/iothub/* $(Build.ArtifactStagingDirectory)/terraform/iothub
      displayName: Copy terraform state (iothub)
      continueOnError: true

    - publish: '$(Build.ArtifactStagingDirectory)/terraform/iothub'
      displayName: 'Publish Terraform state for destroy stage (iothub)'
      continueOnError: true
      artifact: terraformStateIoTHub