name: Container build
description: Build a container and push it to a registry.

inputs:
  registry:
    description: The working directory to execute the command in.
    required: false
    default: ghcr.io
  containers:
    description: The containers to build.
    default: []
  force-push:
    description: Force push the container to the registry.
    default: false

runs:
  using: composite
  steps:
    - name: Setup image
      id: image
      run: |
        dockerfile=${{ inputs.containers }}
        image=${dockerfile#devops/docker/}
        image=${image%/*}
        distro=${image%-*}

        repo=$(echo ${{ github.repository }} | awk '{print tolower($0)}')

        echo name=$(echo -n $repo/$image) >> $GITHUB_OUTPUT
        echo path=$(dirname ${dockerfile}) >> $GITHUB_OUTPUT
        echo distro=$(echo -n $distro) >> $GITHUB_OUTPUT

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker login (ghcr.io)
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ steps.image.outputs.name }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ github.run_number }}
          type=sha

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ${{ steps.image.outputs.path }}
        # Only push the image when a pull request is merged to main or force-push is true
        push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.force-push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}