instance of OsConfigResource as $OsConfigResource0ref
{
    ResourceID = "Ensure NIS Client is not installed";
    PayloadKey = "/cis/ubuntu/22.04/v1.0.0/2/2/1";
    RuleId = "079122c1-4421-5be3-f897-92a1655e9228";
    ComponentName = "ComplianceEngine";
    ProcedureObjectName = "procedureEnsureNISClientIsNotInstalled";
    ProcedureObjectValue = "eyJuYW1lIjoiRW5zdXJlIE5JUyBDbGllbnQgaXMgbm90IGluc3RhbGxlZCIsImF1ZGl0Ijp7Im5vdCI6eyJQYWNrYWdlSW5zdGFsbGVkIjp7InBhY2thZ2VOYW1lIjoibmlzIn19fSwicGFyYW1ldGVycyI6e319";
    InitObjectName = "initEnsureNISClientIsNotInstalled";
    ReportedObjectName = "auditEnsureNISClientIsNotInstalled";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsureNISClientIsNotInstalled";
    DesiredObjectValue = "";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "ComplianceEngineExample";
    SourceInfo = "::4::5::OsConfigResource";
};
instance of OsConfigResource as $OsConfigResource1ref
{
    ResourceID = "Ensure permissions on /etc/crontab are configured";
    PayloadKey = "/cis/ubuntu/22.04/v1.0.0/2/4/1/2";
    RuleId = "65e74f75-0eac-58d0-1a5a-668ccb5c8f35";
    ComponentName = "ComplianceEngine";
    ProcedureObjectName = "procedureEnsurePermissionsOnEtcCrontabAreConfigured";
    ProcedureObjectValue = "eyJuYW1lIjoiRW5zdXJlIHBlcm1pc3Npb25zIG9uIC9ldGMvY3JvbnRhYiBhcmUgY29uZmlndXJlZCIsInJlbWVkaWF0ZSI6eyJhbnlPZiI6W3sibm90Ijp7IlBhY2thZ2VJbnN0YWxsZWQiOnsicGFja2FnZU5hbWUiOiIkQ1JPTl9QS0dfTkFNRSJ9fX0seyJFbnN1cmVGaWxlUGVybWlzc2lvbnMiOnsiZmlsZW5hbWUiOiIvZXRjL2Nyb250YWIiLCJvd25lciI6InJvb3QiLCJncm91cCI6InJvb3QiLCJwZXJtaXNzaW9ucyI6IjYwMCJ9fV19LCJhdWRpdCI6eyJhbnlPZiI6W3sibm90Ijp7IlBhY2thZ2VJbnN0YWxsZWQiOnsicGFja2FnZU5hbWUiOiIkQ1JPTl9QS0dfTkFNRSJ9fX0seyJFbnN1cmVGaWxlUGVybWlzc2lvbnMiOnsiZmlsZW5hbWUiOiIvZXRjL2Nyb250YWIiLCJvd25lciI6InJvb3QiLCJncm91cCI6InJvb3QiLCJwZXJtaXNzaW9ucyI6IjYwMCJ9fV19LCJwYXJhbWV0ZXJzIjp7IkNST05fUEtHX05BTUUiOiJjcm9uIn19";
    InitObjectName = "initEnsurePermissionsOnEtcCrontabAreConfigured";
    ReportedObjectName = "auditEnsurePermissionsOnEtcCrontabAreConfigured";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsurePermissionsOnEtcCrontabAreConfigured";
    DesiredObjectValue = "CRON_PKG_NAME=cron";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "ComplianceEngineExample";
    SourceInfo = "::4::5::OsConfigResource";
};
instance of OsConfigResource as $OsConfigResource2ref
{
    ResourceID = "Ensure permissions on /etc/cron.hourly are configured";
    PayloadKey = "/cis/ubuntu/22.04/v2.0.0/2/4/1/3";
    RuleId = "fb59b8f0-9cf2-19bc-decc-bde4c7f49c7d";
    ComponentName = "ComplianceEngine";
    ProcedureObjectName = "procedureEnsurePermissionsOnEtcCronHourlyAreConfigured";
    ProcedureObjectValue = "eyJuYW1lIjoiRW5zdXJlIHBlcm1pc3Npb25zIG9uIC9ldGMvY3Jvbi5ob3VybHkgYXJlIGNvbmZpZ3VyZWQiLCJhdWRpdCI6eyJhbnlPZiI6W3sibm90Ijp7ImFueU9mIjpbeyJQYWNrYWdlSW5zdGFsbGVkIjp7InBhY2thZ2VOYW1lIjoiJENST05fUEtHX05BTUUifX0seyJQYWNrYWdlSW5zdGFsbGVkIjp7InBhY2thZ2VOYW1lIjoiY3JvbmllIn19XX19LHsiRW5zdXJlRmlsZVBlcm1pc3Npb25zIjp7ImZpbGVuYW1lIjoiL2V0Yy9jcm9uLmhvdXJseSIsIm93bmVyIjoicm9vdCIsImdyb3VwIjoicm9vdCIsInBlcm1pc3Npb25zIjoiNjAwIn19XX0sInBhcmFtZXRlcnMiOnsiQ1JPTl9QS0dfTkFNRSI6ImNyb24ifX0=";
    InitObjectName = "initEnsurePermissionsOnEtcCronHourlyAreConfigured";
    ReportedObjectName = "auditEnsurePermissionsOnEtcCronHourlyAreConfigured";
    ExpectedObjectValue = "PASS";
    DesiredObjectName = "remediateEnsurePermissionsOnEtcCronHourlyAreConfigured";
    DesiredObjectValue = "CRON_PKG_NAME=cron";
    ModuleName = "GuestConfiguration";
    ModuleVersion = "1.0.0";
    ConfigurationName = "ComplianceEngineExample";
    SourceInfo = "::4::5::OsConfigResource";
};
instance of OMI_ConfigurationDocument
{
    Version = "3.0.0";
    CompatibleVersionAdditionalProperties = {"Omi_BaseResource:ConfigurationName"};
    Author = "Microsoft";
    GenerationDate = "06/11/2025 19:53:38 UTC";
    Name = "ComplianceExample";
};
