name: Build Containers

on:
  pull_request:
    paths:
      - devops/docker/**/Dockerfile
      - .github/workflows/build-containers.yml
  push:
    branches:
      - dev
      - main
    paths:
      - devops/docker/**/Dockerfile
      - .github/workflows/build-containers.yml
  workflow_dispatch:
    inputs:
      distro_list:
        description: 'Comma separated list of distros to build. eg. ubuntu-20.04-amd64,ubuntu-20.04-arm64'
        type: string
      rebuild_all:
        description: 'Rebuild all containers'
        default: false
        type: boolean

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  BUILD_TYPE: Release
  MOUNT: /kompli

jobs:
  modified-containers:
    name: Modified containers
    runs-on: ubuntu-latest
    outputs:
      containers: ${{ steps.matrix.outputs.containers }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          submodules: true

      - name: Create build matrix
        id: matrix
        run: |
          containers=$(ls -d devops/docker/**/Dockerfile | jq -R . | jq -s .)

          echo Containers to build: $containers
          echo containers=$containers >> $GITHUB_OUTPUT

  docker-build:
    name: Docker
    needs: modified-containers
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        container: ${{ fromJson(needs.modified-containers.outputs.containers) }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          submodules: true
      - name: Setup image
        id: image
        run: |
          dockerfile=${{ matrix.container }}
          image=${dockerfile#devops/docker/}
          image=${image%/*}
          distro=${image%-*}

          repo=$(echo ${{ github.repository }} | awk '{print tolower($0)}')

          echo name=$(echo -n $repo/$image) >> $GITHUB_OUTPUT
          echo path=$(dirname ${dockerfile}) >> $GITHUB_OUTPUT
          echo distro=$(echo -n $distro) >> $GITHUB_OUTPUT
          echo "image=$image" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55

      - name: Docker login (ghcr.io)
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9
        with:
          images: ${{ env.REGISTRY }}/${{ steps.image.outputs.name }}
          tags: |
            type=sha,enable=true,priority=900,prefix=sha256-,suffix=,format=long
            type=schedule,enable=true,priority=10,prefix=date-,suffix=,pattern=nightly
            type=raw,value=git-${{ github.sha }}
            type=raw,value=run-${{ github.run_number }}

      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: .
          file: ${{ steps.image.outputs.path }}/Dockerfile
          # Always push the new image. We use frozen checksums stored in test-matrix.json. A new-test-matrix.json will be dropped in the artifacts which can be used to update the existing file after confirming the CI works.
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Save digest
        run: |
          DIGEST_SHA=${{ steps.build_and_push.outputs.digest }}
          DIGEST_SHA=$(echo ${DIGEST_SHA} |  sed -e 's#^sha256:\(.*\)#@sha256:\1#')
          GIT_LABEL=$(echo '${{ steps.meta.outputs.json }}' | jq -r '.tags [] |select (contains(":git-"))')
          jq --null-input \
          --arg distibution "${{ steps.image.outputs.distro }}" \
          --arg digest_sha "${DIGEST_SHA}" \
          --arg git_label "${GIT_LABEL}" \
          '{"name": $distibution, "arch": "amd64", "tag": $digest_sha, "git_label": $git_label }' > digest-${{ steps.image.outputs.distro }}.json
          cat digest-${{ steps.image.outputs.distro }}.json

      - name: Upload digest
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          overwrite: true
          name: digest-${{ steps.image.outputs.distro }}
          path: digest-*.json
          retention-days: 1


  post-build:
    name: Post-Build Digest Collector
    needs: [modified-containers, docker-build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all digests artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          path: all-digests
          pattern: digest-*
          merge-multiple: true

      - name:  Combine all digest artifacts
        run: |
          rm new-test-matrix.json || true
          function concatenate_digest() {
            FILES=( $(find all-digests -name 'digest-*.json' | sort) )
            echo "["
            last=$((${#FILES[@]}-1))
            for((i = 0; i < ${#FILES[@]}; i++)); do
                # ORS sets the output separator to noting, and than just print file
                awk 'BEGIN{ORS=""} {print}' "${FILES[$i]}" ;
                # add newline or comman
                if [[ ${i} -eq ${last} ]] ; then
                    echo ""
                else
                    echo ","
                fi
            done
            echo "]"
            }
            concatenate_digest > new-test-matrix.json
            cat new-test-matrix.json

      - name: Upload New Test Matrix
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: new-test-matrix.json
          path: new-test-matrix.json
