name: CI Report

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  unit-test-report:
    name: Unit Test Report
    runs-on: ubuntu-latest
    steps:
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test report
          path: ./test-output/*.xml
          reporter: java-junit

  coverage-report:
    name: Coverage Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: code-coverage

      - name: Create coverage report
        uses: ./.github/actions/check-run
        with:
          name: Coverage report
          title: Code coverage
          markdown: code-coverage-results.md