name: CI Report

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  coverage-report:
    name: Coverage Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: code-coverage

      - name: Create coverage report
        uses: ./.github/actions/check-run
        with:
          name: Coverage report
          title: Code coverage
          markdown: code-coverage-results.md