name: CI Report

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: unit-test
          name: CI report
          path: '*.xml'
          reporter: java-junit
