name: E2E Report

on:
  workflow_run:
    workflows: ['E2E']
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@d61b558e8df85cb60d09ca3e5b09653b4477cea7 # v1
        with:
          artifact: e2e-report
          name: E2E Report
          path: '*.trx'
          reporter: dotnet-trx
