name: Fetch Test Targets
on:
  workflow_call:
    inputs:
      environment:
        description: The name of the target environment
        type: string
        required: true
      location:
        description: The location for the resource group
        type: string
        required: false
        default: eastus
    outputs:
      distroName: 
        description: The name of the dsitro
        value: ${{ jobs.fetch-targets.outputs.distroName }}
      resourceGroupName:
        description: The name of the resource group
        value: ${{ jobs.fetch-targets.outputs.resourceGroupName }}

jobs:
  fetch-targets:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      distroName: ${{ steps.set-matrix.outputs.distroName }}
      resourceGroupName: ${{ steps.set-resource-group.outputs.resourceGroupName }}

    steps:
      - uses: actions/checkout@v3

      - name: Read E2E target environment definitions
        id: set-matrix
        run: |
          distroName=`cat ./devops/e2e/${{ secrets.E2E_ENV_FILE }} | jq '.[].distroName' | jq -s .`
          echo ::set-output name=distroName::${distroName}

      - name: Generate random resource group name
        id: set-resource-group
        run: |
          resourceGroupName=`echo osconfig-$(echo $RANDOM | md5sum | head -c 16)`
          echo ::set-output name=resourceGroupName::${resourceGroupName}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create resource group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --name ${{ steps.set-resource-group.outputs.resourceGroupName }} --location ${{ inputs.location }} --tags environment="osconfig-e2etest"
