name: Code Formatting

on: [push, pull_request]

permissions:
  contents: read

jobs:
  code-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
    - name: Set up Python 3.8
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      with:
        python-version: 3.8
    - name: Install clang tools
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format clang-tidy
      run: |
        devops/scripts/run-hooks.sh --install
        devops/scripts/run-hooks.sh --all-files
