name: Code Formatting

on: [push, pull_request]

permissions:
  contents: read

jobs:
  code-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
    - name: Set up Python 3.8
      uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e
      with:
        python-version: 3.8
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files
