name: Fuzzer execution

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      arch:
        required: true
        type: string
      package-type:
        required: true
        type: string
      trigger:
        description: The event name that triggered this workflow.
        required: true
        type: string
      container-tag:
        type: string
        required: false
        default: latest

env:
  MOUNT: /azure-osconfig
  REGISTRY: ghcr.io
  WF_DISPATCH_TIMEOUT: 3600
  PR_DISPATCH_TIMEOUT: 300

jobs:
  package:
    uses: ./.github/workflows/package-build.yml
    with:
      target: ${{ inputs.target }}
      arch: ${{ inputs.arch }}
      artifact: ${{ inputs.target }}-fuzzer
      package-type: ${{ inputs.package-type }}
      build-fuzzers: true

  fuzzer-execution:
    needs: package
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        id: download
        with:
          name: ${{ inputs.target }}-fuzzer

      - name: Run container
        id: container
        uses: ./.github/actions/container-run
        with:
          registry: ${{ env.REGISTRY }}
          container: azure/azure-osconfig/${{ inputs.target }}-${{ inputs.arch }}
          mount: ${{ github.workspace }}:${{ env.MOUNT }}
          tag: ${{ inputs.container-tag }}

      - name: Install prerequisites
        uses: ./.github/actions/container-exec
        with:
          container: ${{ steps.container.outputs.id }}
          working-directory: ${{ env.MOUNT }}/tests/fuzzer
          cmd: mkdir -p ${{ env.MOUNT }}/output/artifacts && mkdir /tmp/corpus && cp -r ${{ env.MOUNT }}/src/tests/fuzzer/seed_corpus/* /tmp/corpus && chmod u+x ./osconfig-fuzzer

      - if: ${{ inputs.trigger == 'workflow_dispatch' }}
        name: Run osconfig-fuzzer
        uses: ./.github/actions/container-exec
        with:
          container: ${{ steps.container.outputs.id }}
          working-directory: ${{ env.MOUNT }}/tests/fuzzer
          cmd: set -o pipefail && ./osconfig-fuzzer -artifact_prefix=${{ env.MOUNT }}/output/artifacts/ -max_total_time=${{ env.WF_DISPATCH_TIMEOUT }} /tmp/corpus 2>&1 >/dev/null | tee ${{ env.MOUNT }}/output/osconfig-fuzzer.log

      - if: ${{ inputs.trigger == 'pull_request' }}
        name: Run osconfig-fuzzer
        uses: ./.github/actions/container-exec
        with:
          container: ${{ steps.container.outputs.id }}
          working-directory: ${{ env.MOUNT }}/tests/fuzzer
          cmd: set -o pipefail && ./osconfig-fuzzer -artifact_prefix=${{ env.MOUNT }}/output/artifacts/ -max_total_time=${{ env.PR_DISPATCH_TIMEOUT }} /tmp/corpus 2>&1 >/dev/null | tee ${{ env.MOUNT }}/output/osconfig-fuzzer.log

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: ${{ inputs.target }}-logs
          path: ${{ github.workspace }}/output
