name: Code coverage testing

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      arch:
        required: true
        type: string
      package-type:
        required: true
        type: string
      excluded-tests:
        required: false
        description: 'A regex pattern of tests to exclude.'
        type: string

env:
  MOUNT: /azure-osconfig
  REGISTRY: ghcr.io

jobs:
  package:
    uses: ./.github/workflows/package-build.yml
    with:
      target: ${{ inputs.target }}
      arch: ${{ inputs.arch }}
      artifact: ${{ inputs.target }}
      package-type: ${{ inputs.package-type }}
      build-coverage: true
      test: true
      build-type: Debug

  test:
    needs: package
    runs-on: [self-hosted, 1ES.Pool=e2e-pool, '1ES.ImageOverride=${{ inputs.target }}']
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          clean: true

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # - name: Setup QEMU
      #   if: ${{ matrix.target.arch != 'amd64' }}
      #   uses: docker/setup-qemu-action@v3

      - name: Run container
        id: container
        uses: ./.github/actions/container-run
        with:
          registry: ${{ env.REGISTRY }}
          container: azure/azure-osconfig/${{ inputs.target }}-amd64
          mount: ${{ github.workspace }}:${{ env.MOUNT }}
          tag: latest

      - name: Generate build
        uses: ./.github/actions/container-exec
        with:
          container: ${{ steps.container.outputs.id }}
          cmd: |
            mkdir build && cd build
            cmake ../src -DCMAKE_C_COMPILER="/usr/bin/gcc" -DCMAKE_CXX_COMPILER="/usr/bin/g++" -DCMAKE_build-type=Debug -Duse_prov_client=ON -Dhsm_type_symm_key=ON -DCOMPILE_WITH_STRICTNESS=ON -DBUILD_TESTS=ON -DBUILD_SAMPLES=ON -DBUILD_ADAPTERS=ON -Duse_default_uuid=ON -DCOVERAGE=ON -DBUILD_TESTS=ON

      - name: Build azure-osconfig
        uses: ./.github/actions/container-exec
        with:
          container: ${{ steps.container.outputs.id }}
          working-directory: ${{ env.MOUNT }}/build
          cmd: cmake --build . --config Debug --parallel

      - name: Create osconfig.json
        run: |
          sudo mkdir -p /etc/osconfig
          sudo cp -r ./src/adapters/pnp/daemon/osconfig.json /etc/osconfig/osconfig.json

      - name: Defer test execution
        uses: ./.github/actions/defer-tests

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcovr gcc

      - name: Run moduletest
        working-directory: ${{ steps.download.outputs.download-path }}/modules/test
        run: |
          sudo chmod +x ./moduletest

          result=0
          recipes=$(find ../../src/modules/test/recipes/ -name "*.json")

          for recipe in $recipes; do
            modules=$(cat $recipe | grep '\.so' | awk -F'"' '{print $4}')
            if [ -z "$modules" ]; then
              echo "no modules found in $recipe"
              continue
            fi

            skip=
            for module in $modules; do
              echo "module: $module"
              if [ ! -f ../bin/$module ]; then
                echo "module $module lodaed in recipe $recipe not found"
                skip=1
                break
              fi
            done

            if [ ! -z "$skip" ]; then
              echo "skipping recipe $recipe"
              continue
            fi

            name=$(basename $recipe | tr '[:upper:]' '[:lower:]' | sed 's/\.[^.]*$//' | sed 's/\(test\|tests\)$//')
            echo -n "testing $name ... "

            if output=$(sudo ./moduletest $recipe --bin ../bin); then
              echo passed
            else
              echo failed
              result=1
              echo "::warning file=$name.log::Error(s) in module-test for '$name'"
            fi

            echo "$output"
            echo "$output" > ../../$name.log
          done

          exit $result

      - name: Run gcovr
        working-directory: ${{ steps.download.outputs.download-path }}
        run: |
          find . -name '*\.gcda' -exec echo "GCDA file: {}" \;
          find . -name '*\.gcno' -exec echo "GCNO file: {}" \;
          gcovr --root ${{ steps.download.outputs.download-path }} --html-details -o ${{ steps.download.outputs.download-path }}/coverage.html --xml-pretty --xml ${{ steps.download.outputs.download-path }}/coverage.xml --gcov-executable gcov --exclude '.*test.*' --exclude azure-iot-sdk-c --gcov-ignore-parse-errors

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: ${{ inputs.target }}-logs
          path: '*.log'

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: ${{ inputs.target }}-coverage
          path: 'coverage.*'
