name: Build 'OSConfig for MC' (NRP and policy packages)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to publish'
        required: true
        default: main
        type: string
  push:
    # tags:
    #   - v*.*.*

jobs:
  publish:
    name: Publish
    uses: ./.github/workflows/nrp-build.yml
    strategy:
      matrix:
        target:
          [
            { os: ubuntu, version: 14.04, arch: amd64, dist: trusty, package-type: DEB },
          ]
    with:
      release-name: Test Azure Policy Packages
      target: ${{ matrix.target.os }}-${{ matrix.target.version }}
      arch: ${{ matrix.target.arch }}
      dist: ${{ matrix.target.dist }}
      environment: prod
      package-type: ${{ matrix.target.package-type }}
      buildOsConfigForMc: true
    secrets: inherit
