name: Build 'OSConfig for MC' (NRP and policy packages)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to publish'
        required: true
        default: main
        type: string

jobs:
  publish:
    name: Publish
    uses: ./.github/workflows/package-build.yml
    strategy:
      matrix:
        target:
          [
            { os: ubuntu, version: 14.04, arch: amd64, dist: trusty, package-type: DEB },
          ]
    with:
      target: ${{ matrix.target.os }}-${{ matrix.target.version }}
      arch: ${{ matrix.target.arch }}
      artifact: ${{ matrix.target }}-${{ matrix.arch }}
      package-type: ${{ matrix.target.package-type }}
      machine-config: true
      release: true
    # secrets: inherit
