name: Module Test

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      arch:
        required: true
        type: string
      package-type:
        required: true
        type: string
      excluded-tests:
        required: false
        description: 'A regex pattern of tests to exclude.'
        type: string

jobs:
  package:
    uses: ./.github/workflows/package-build.yml
    with:
      target: ${{ inputs.target }}
      arch: ${{ inputs.arch }}
      artifact: ${{ inputs.target }}
      package-type: ${{ inputs.package-type }}
      test: true

  test:
    needs: package
    runs-on: [self-hosted, 1ES.Pool=e2e-pool, '1ES.ImageOverride=${{ inputs.target }}']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        id: download
        with:
          name: ${{ inputs.target }}

      - name: Create osconfig.json
        run: |
          sudo mkdir -p /etc/osconfig
          sudo cp -r ./src/adapters/pnp/daemon/osconfig.json /etc/osconfig/osconfig.json

      - name: Run moduletest
        working-directory: ${{ steps.download.outputs.download-path }}/modules/test
        run: |
          sudo chmod +x ./moduletest

          result=0
          recipes=$(ls -d ../../src/modules/test/recipes/*.json)

          for recipe in $recipes; do
            name=$(basename $recipe | tr '[:upper:]' '[:lower:]' | sed 's/\.[^.]*$//' | sed 's/\(test\|tests\)$//')

            if $(echo $recipe | grep -q -E "${{ inputs.excluded-tests }}"); then
              echo "skipping $name (excluded)"
              continue
            fi

            echo -n "testing $name ... "

            sudo ./moduletest $recipe --bin ../bin > ${{ inputs.target }}-${{ inputs.arch }}-$name-testResult.log 2>&1
            ls -l
          done

          exit $result

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: ${{ inputs.target }}-${{ inputs.arch }}-report
          path: '${{ steps.download.outputs.download-path }}/*testResult.log'