name: Nightly

on:
  # Push events are for pre-release only
  # (this should really be a "preview" of an upcoming prod release i.e. insiders-slow or equivalent)
  push:
    # branches:
    #   - "release/**"
  # schedule:
  #   - cron: "0 8 * * *"  # Every day at 8:00 am UTC

env:
  package: insiders-fast

jobs:
  check-changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      new: ${{ steps.commits.outputs.new }}
    steps:
      - name: Check last commit
        id: commits
        run: |
          date=$(gh api graphql -F owner='Azure' -F name='azure-osconfig' -f query='
            query($name: String!, $owner: String!) {
              repository(name: $name, owner: $owner) {
                defaultBranchRef {
                  target {
                    ... on Commit {
                      pushedDate
                    }
                  }
                }
              }
            }' | jq .data.repository.defaultBranchRef.target.pushedDate | sed 's/"//g')

          # Only publish a new package if changes have been made since the last package was published

          cutoff=$(date -d '1 day ago' +%s)
          age=$(date -d "$date" +%s)
          if (($age > $cutoff))
          then
            echo new=true >> $GITHUB_OUTPUT
          else
            echo ::warning title="No changes since last nightly package" "Last change was committed on $date. Skipping nightly package."
            echo new=false >> $GITHUB_OUTPUT
          fi

  package:
    name: Package
    needs: check-changes
    if: needs.check-changes.outputs.new == 'true'
    uses: ./.github/workflows/package-build.yml
    with:
      artifact: ${{ env.package }}

  signing:
    name: Signing
    needs: package
    uses: ./.github/workflows/package-signing.yml
    with:
      artifact: ${{ env.package }}

  publish:
    name: Publish
    needs: signing
    uses: ./.github/workflows/package-publish.yml
    with:
      artifact: ${{ needs.signing.outputs.artifact }}
      channel: ${{ env.package }}


  # TODO: if the workflow was triggered by a push to release/**, create/update a github pre-release,
  # ideally this stage will be a separate workflow later (possibly publishing on insiders-slow channel)
  # if a release does not exist with the same tag, create a new release

  # pre-release:
  #   name: Pre-release
  #   needs: signing
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/')
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Release version
  #       id: version
  #       run: |
  #         version=$(echo ${{ github.ref }} | sed 's/refs\/heads\/release\///g')
  #         echo ::set-output name=version::$version

  #     - name: Create/update

  #     # TODO: check if this version already exists as a published release

  #     # TODO: automated changelog generation

  #     - run: echo "Creating/updating GitHub Pre-Release for ${{ steps.version.outputs.version }}"