name: Publish Package

on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
      artifact:
        required: true
        type: string

jobs:
  publish:
    runs-on: [self-hosted, 1ES.Pool=release-pool, 1ES.ImageOverride=ubuntu-22.04]
    environment: ${{ inputs.channel }}
    steps:
      - name: Download repoclient
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          AZURE_VAULT: ${{ secrets.AZURE_VAULT }}
          REPOCLIENT_KEY: ${{ secrets.REPOCLIENT_KEY }}
        run: |
          mkdir -p ~/.repoclient

          az login --service-principal --username "$CLIENT_ID" --password "$CLIENT_SECRET" --tenant "$TENANT_ID"

          az keyvault secret download --encoding utf-8 \
            --file "~/.repoclient/private.pem" \
            --name "$REPOCLIENT_KEY" \
            --vault-name "$AZURE_VAULT"

          az storage blob download \
            --account-name osconfig \
            -c azure-repoapi-client \
            -n azure-repoapi-client_2.0.1_amd64.deb \
            -f repoclient.deb

      - name: Install repoclient
        run: |
          sudo apt-get install python3-adal --yes
          sudo dpkg -i repoclient.deb
          rm repoclient.deb

      - name: Configure repoclient
        run: |
          config=$(cat <<EOF
          {
              "AADResource": "https://microsoft.onmicrosoft.com/945999e9-da09-4b5b-878f-b66c414602c0",
              "AADTenant": "72f988bf-86f1-41af-91ab-2d7cd011db47",
              "AADAuthorityUrl": "https://login.microsoftonline.com",
              "server": "azure-apt-cat.cloudapp.net",
              "port": "443",
              "AADClientId": "${{ secrets.AAD_CLIENT_ID }}"
              "AADClientCertificate": "~/.repoclient/private.pem",
              "repositoryId": "osconfig"
          }
          EOF
          )

          echo "$config" > config.json

      - uses: actions/download-artifact@v3
        id: package
        with:
          name: ${{ inputs.artifact }}
          path: packages

      # - name: Publish
      #   env:
      #     REPO_ID_ubuntu-18_04: ${{ secrets.REPO_ID_BIONIC }}
      #     REPO_ID_ubuntu-20_04: ${{ secrets.REPO_ID_FOCAL }}
      #     REPO_ID_debian-10: ${{ secrets.REPO_ID_BUSTER }}
      #     REPO_ID_debian-11: ${{ secrets.REPO_ID_BULLSEYE }}
      #   run: |
      #     target=$(echo ${{ inputs.target }} | tr . _)
      #     repo_id=$(eval echo "\$REPO_ID_$target")

      #     repoclient -v v3 -c config.json package add --check --wait 300 packages -r $repo_id
