name: Sign Package

on:
  workflow_call:
    inputs:
      artifact:
        description: The artifact containing the packages to be signed.
        type: string
        required: true

jobs:
  sign:
    runs-on: [self-hosted, 1ES.Pool=release-pool, 1ES.ImageOverride=windows-2022]
    steps:
      - uses: actions/checkout@v3

      - name: Setup ESRP
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          AZURE_VAULT: ${{ secrets.AZURE_VAULT }}
          AUTH_CERT: ${{ secrets.AZURE_VAULT_AUTH_CERT_NAME }}
          REQUEST_SIGNING_CERT: ${{ secrets.AZURE_VAULT_REQUEST_SIGNING_CERT_NAME }}
        run: |
          az login --service-principal --username "$env:CLIENT_ID" --password "$env:CLIENT_SECRET" --tenant "$env:TENANT_ID"

          az keyvault secret download --vault-name "$env:AZURE_VAULT" --name "$env:AUTH_CERT" --file out.pfx
          certutil -f -importpfx out.pfx
          Remove-Item -Path out.pfx

          az keyvault secret download --vault-name "$env:AZURE_VAULT" --name "$env:REQUEST_SIGNING_CERT" --file out.pfx
          certutil -f -importpfx out.pfx
          Remove-Item -Path out.pfx

      - name: Sign package
        uses: ./.github/actions/sign-package
        env:
          AAD_ID: ${{ secrets.ESRP_AAD_ID }}
          LINUX_KEY_CODE: ${{ secrets.ESRP_LINUX_KEY_CODE }}
          LINUX_OP_CODE: ${{ secrets.ESRP_LINUX_OP_CODE }}
        with:
          artifact: ${{ inputs.artifact }}
