name: Sign Package

on:
  workflow_call:
    inputs:
      artifact:
        description: The artifact containing the packages to be signed.
        type: string
        required: true
      key-code:
        description: The signing key-code to use.
        type: string
        required: true
      package-type:
        type: string
        required: true

jobs:
  sign:
    runs-on: [self-hosted, 1ES.Pool=release-pool, 1ES.ImageOverride=windows-2022]
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup ESRP
        env:
          AZURE_VAULT: ${{ secrets.AZURE_VAULT }}
          AUTH_CERT: ${{ secrets.AZURE_VAULT_AUTH_CERT_NAME }}
          REQUEST_SIGNING_CERT: ${{ secrets.AZURE_VAULT_REQUEST_SIGNING_CERT_NAME }}
        run: |
          az keyvault secret download --vault-name "$env:AZURE_VAULT" --name "$env:AUTH_CERT" --file out.pfx
          certutil -f -importpfx out.pfx
          Remove-Item -Path out.pfx

          az keyvault secret download --vault-name "$env:AZURE_VAULT" --name "$env:REQUEST_SIGNING_CERT" --file out.pfx
          certutil -f -importpfx out.pfx
          Remove-Item -Path out.pfx

      - name: Sign package
        uses: ./.github/actions/sign-package
        env:
          AAD_ID: ${{ secrets.ESRP_AAD_ID }}
          LINUX_KEY_CODE: ${{ inputs.key-code }}
          LINUX_OP_CODE: ${{ secrets.ESRP_LINUX_OP_CODE }}
        with:
          artifact: ${{ inputs.artifact }}
          package-type: ${{ inputs.package-type }}
