name: Sign Package

on:
  workflow_call:
    inputs:
      artifact:
        description: The artifact containing the packages to be signed.
        type: string
        required: true

jobs:
  esrp:
    runs-on: [self-hosted, 1ES.Pool=release-pool, 1ES.ImageOverride=windows-2022]
    steps:
      - uses: actions/checkout@v3

      - name: Setup ESRP
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          AZURE_VAULT: ${{ secrets.AZURE_VAULT }}
          AUTH_CERT: ${{ secrets.AZURE_VAULT_AUTH_CERT_NAME }}
          REQUEST_SIGNING_CERT: ${{ secrets.AZURE_VAULT_REQUEST_SIGNING_CERT_NAME }}
        run: |
          az login --service-principal --username "$env:CLIENT_ID" --password "$env:CLIENT_SECRET" --tenant "$env:TENANT_ID"

          az storage blob download --file esrp.zip --auth-mode login --account-name osconfig --container esrpclient --name esrpclient.zip
          Expand-Archive -Path esrp.zip -DestinationPath .\esrp

          az keyvault secret download --vault-name "$env:AZURE_VAULT" --name "$env:AUTH_CERT" --file aadCert.pfx
          az keyvault secret download --vault-name "$env:AZURE_VAULT" --name "$env:REQUEST_SIGNING_CERT" --file esrpCert.pfx

          Set-Location -Path cert:\CurrentUser\My
          Import-PfxCertificate -FilePath ${{ github.workspace }}\aadCert.pfx
          Import-PfxCertificate -FilePath ${{ github.workspace }}\esrpCert.pfx
          Remove-Item -Path ${{ github.workspace }}\aadCert.pfx
          Remove-Item -Path ${{ github.workspace }}\esrpCert.pfx

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: esrp/unsigned

      - name: Run esrpclient
        working-directory: .\esrp
        run: |
          mkdir signed

          $auth = ".\Config\Auth.json"
          $config = ".\Config\Config.json"
          $policy = ".\Config\Policy.json"
          $output = "Output\output.json"
          $src = "${{ github.workspace }}\esrp\unsigned"
          $dst = "${{ github.workspace }}\esrp\signed"

          .\Config\createJob.ps1 (ls unsigned\*.deb | select -expand Name) $src $dst

          cat Job.json

          .\EsrpClient.exe Sign -a $auth -c $config -i "Job.json" -p $policy -o $output -l Verbose -f esrp.log

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact }}-signed
          path: .\esrp\signed

      - uses: actions/upload-artifact@v3
        with:
          name: esrp
          path: ${{ github.workspace }}\esrp\esrp.log
