name: Publish Package

on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
      target:
        required: true
        type: string
      artifact:
        required: true
        type: string

jobs:
  publish:
    runs-on: [self-hosted, 1ES.Pool=release-pool, 1ES.ImageOverride=ubuntu-22.04]
    environment: ${{ inputs.channel }}
    env:
      PMC_CLI_BASE_URL: ${{ secrets.PMC_CLI_BASE_URL }}
      PMC_CLI_MSAL_CLIENT_ID: ${{ secrets.PMC_CLI_MSAL_CLIENT_ID }}
      PMC_CLI_MSAL_SCOPE: ${{ secrets.PMC_CLI_MSAL_SCOPE }}
      PMC_CLI_MSAL_AUTHORITY: ${{ secrets.PMC_CLI_MSAL_AUTHORITY }}
      PMC_CLI_MSAL_CERT_PATH: auth.pem

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: packages

      - name: Download certs
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          AZURE_VAULT: ${{ secrets.AZURE_VAULT }}
          PMC_MSAL_CERT_NAME: ${{ secrets.PMC_MSAL_CERT_NAME }}
        run: |
          az login --service-principal --username "$CLIENT_ID" --password "$CLIENT_SECRET" --tenant "$TENANT_ID"
          az keyvault secret download --vault-name "$AZURE_VAULT" --name "$PMC_MSAL_CERT_NAME" --file "${{ github.workspace }}/auth.pem"

      - name: Set target
        id: target
        env:
          REPO_ID_ubuntu_1804: ${{ secrets.REPO_ID_BIONIC }}
          REPO_ID_ubuntu_2004: ${{ secrets.REPO_ID_FOCAL }}
          REPO_ID_debian_10: ${{ secrets.REPO_ID_BUSTER }}
          REPO_ID_debian_11: ${{ secrets.REPO_ID_BULLSEYE }}
        run: |
          target=$(echo ${{ inputs.target }} | tr - _ | tr -d .)
          repo_id=$(eval echo "\$REPO_ID_$target")
          echo "id=$repo_id" >> $GITHUB_OUTPUT

      - name: Upload package
        id: upload
        uses: ./.github/actions/pmc
        with:
          command: package upload ./packages

      - name: Update repo
        uses: ./.github/actions/pmc
        with:
          command: repo package update --add-packages ${{ steps.upload.outputs.result }} ${{ steps.target.outputs.id }}
