name: Publish Package

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      channel:
        required: true
        type: string
      artifact:
        required: true
        type: string

jobs:
  publish:
    runs-on: [self-hosted, 1ES.Pool=release-pool, 1ES.ImageOverride=ubuntu-22.04]
    env:
      PMC_CLI_BASE_URL: https://pmc-ingest.trafficmanager.net/api/v4
      PMC_CLI_MSAL_CLIENT_ID: 7497d560-834a-4326-9750-ead7c3894d19
      PMC_CLI_MSAL_SCOPE: api://d48bb382-20ec-41b9-a0ea-07758a21ccd0/.default
      PMC_CLI_MSAL_AUTHORITY: https://login.microsoftonline.com/MSAzureCloud.onmicrosoft.com
      PMC_CLI_MSAL_CERT_PATH: auth.pem

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: packages

      - name: Download certs
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          AZURE_VAULT: ${{ secrets.AZURE_VAULT }}
          PMC_MSAL_CERT_NAME: pmc-onecert
        run: |
          az login --service-principal --username "$CLIENT_ID" --password "$CLIENT_SECRET" --tenant "$TENANT_ID"
          az keyvault secret download --vault-name "$AZURE_VAULT" --name "$PMC_MSAL_CERT_NAME" --file "${{ github.workspace }}/auth.pem"

      - name: Upload package
        id: upload
        uses: ./.github/actions/pmc
        with:
          command: --id-only package upload ./packages

      - name: Update repo
        uses: ./.github/actions/pmc
        with:
          command: repo package update --add-packages ${{ steps.upload.outputs.result }} ${{ inputs.repo }} ${{ inputs.channel }}

      - name: Publish package
        uses: ./.github/actions/pmc
        with:
          command: repo publish ${{ inputs.repo }}
