name: Publish (prod)

on: [workflow_dispatch]

jobs:
  publish:
    name: Publish
    uses: ./.github/workflows/publish.yml
    strategy:
      matrix:
        target:
          [
            { os: debian, version: 10, arch: amd64, dist: buster, package-type: DEB, repo: microsoft-debian-buster-prod-apt },
            { os: debian, version: 10, arch: arm64, dist: buster, package-type: DEB, repo: microsoft-debian-buster-prod-apt },
            { os: debian, version: 11, arch: amd64, dist: bullseye, package-type: DEB, repo: microsoft-debian-bullseye-prod-apt },
            { os: debian, version: 11, arch: arm64, dist: bullseye, package-type: DEB, repo: microsoft-debian-bullseye-prod-apt },
            { os: debian, version: 12, arch: amd64, dist: bookworm, package-type: DEB, repo: microsoft-debian-bookworm-prod-apt },
            { os: debian, version: 12, arch: arm64, dist: bookworm, package-type: DEB, repo: microsoft-debian-bookworm-prod-apt },
            { os: ubuntu, version: 20.04, arch: amd64, dist: focal, package-type: DEB, repo: microsoft-ubuntu-focal-prod-apt },
            { os: ubuntu, version: 20.04, arch: arm64, dist: focal, package-type: DEB, repo: microsoft-ubuntu-focal-prod-apt },
            { os: ubuntu, version: 22.04, arch: amd64, dist: jammy, package-type: DEB, repo: microsoft-ubuntu-jammy-prod-apt },
            { os: ubuntu, version: 22.04, arch: arm64, dist: jammy, package-type: DEB, repo: microsoft-ubuntu-jammy-prod-apt },
          ]
    with:
      target: ${{ matrix.target.os }}-${{ matrix.target.version }}
      arch: ${{ matrix.target.arch }}
      repo: ${{ matrix.target.repo }}
      dist: ${{ matrix.target.dist }}
      # ESRP debian based repos (deb) have channels/rings on repos.
      # ESRP yum based repos (rpm) have no channels
      channel: ${{ matrix.target.package-type == 'DEB' && 'prod' || '' }}
      package-type: ${{ matrix.target.package-type }}
    secrets: inherit
