name: Publish (prod)

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Publish
    uses: ./.github/workflows/publish.yml
    strategy:
      matrix:
        target:
          [
            { os: ubuntu, version: 18.04, dist: bionic, package-type: DEB },
            { os: ubuntu, version: 20.04, dist: focal, package-type: DEB },
            { os: ubuntu, version: 22.04, dist: jammy, package-type: DEB },
            { os: debian, version: 10, dist: buster, package-type: DEB },
            { os: debian, version: 11, dist: bullseye, package-type: DEB },
          ]
        arch: [arm, arm64, amd64]
        exclude:
          - target: { os: ubuntu, version: 22.04, dist: jammy, package-type: DEB }
            arch: arm
    with:
      target: ${{ matrix.target.os }}-${{ matrix.target.version }}
      arch: ${{ matrix.arch }}
      repo: microsoft-${{ matrix.target.os }}-${{ matrix.target.dist }}-prod-apt
      dist: ${{ matrix.target.dist }}
      package-type: ${{ matrix.target.package-type }}
    secrets: inherit

  release:
    name: Release
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: ubuntu-18.04-signed
          path: packages

      - uses: actions/download-artifact@v3
        with:
          name: ubuntu-20.04-signed
          path: packages

      - uses: actions/download-artifact@v3
        with:
          name: ubuntu-22.04-signed
          path: packages

      - uses: actions/download-artifact@v3
        with:
          name: debian-10-signed
          path: packages

      - uses: actions/download-artifact@v3
        with:
          name: debian-11-signed
          path: packages

      - name: Create release
        working-directory: packages
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} \
            --repo ${{ github.repository }} \
            --title "${{ github.ref_name }}" \
            --target ${{ github.sha }} \
            --generate-notes \
            --latest \
            *.deb
