name: Publish

on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true
      arch:
        type: string
        required: true
      dist:
        type: string
        required: true
      repo:
        type: string
        required: true
      channel:
        type: string
        required: true
      package-type:
        type: string
        required: true
      environment:
        type: string
        description: The GitHub environment to use for the build.
        required: true
      container-tag:
        type: string
        required: false
        default: latest

jobs:
  package:
    uses: ./.github/workflows/package-build.yml
    with:
      target: ${{ inputs.target }}
      arch: ${{ inputs.arch }}
      artifact: ${{ inputs.target }}-${{ inputs.arch }}
      package-type: ${{ inputs.package-type }}
      container-tag: ${{ inputs.container-tag }}
      release: true

  sign:
    uses: ./.github/workflows/package-sign.yml
    needs: package
    with:
      artifact: ${{ inputs.target }}-${{ inputs.arch }}
      key-code: ${{ inputs.dist == 'azurelinux' && 'CP-459159-Pgp' || 'CP-450779-Pgp' }}
      package-type: ${{ inputs.package-type }}
    secrets: inherit

  publish:
    uses: ./.github/workflows/package-publish-pmc.yml
    needs: sign
    with:
      repo: ${{ inputs.repo }}
      environment: ${{ inputs.environment }}
      channel: ${{ inputs.channel }}
      artifact: ${{ inputs.target }}-${{ inputs.arch }}-signed
    secrets: inherit
