name: Release

on: workflow_dispatch

# REVIEW: maybe use the release trigger to publish artifacts from the GitHub release

env:
  PACKAGE: prod
  REGISTRY: ghcr.io

jobs:
  # TODO: only run this workflow from a specific "release/**" branch

  package:
    uses: ./.github/workflows/package-build.yml
    strategy:
      matrix:
        # os: [ubuntu-18.04, ubuntu-20.04, debian-10, debian-11]
        os: [ubuntu18.04, ubuntu20.04, debian10, debian11]
        arch: [arm, arm64, amd64]
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}

  signing:
    name: Signing
    needs: package
    uses: ./.github/workflows/package-sign.yml
    with:
      artifact: ${{ env.PACKAGE }}

  validate:
    name: Validate
    needs: signing
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "TODO: validate packages install here"

  publish:
    name: Publish
    needs: signing
    uses: ./.github/workflows/package-publish.yml
    with:
      artifact: ${{ needs.signing.outputs.artifact }}
      channel: ${{ env.PACKAGE }}

  sources:
    name: Sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          clean: true

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Run container
        id: container
        uses: ./.github/actions/container-run
        with:
          registry: ${{ env.REGISTRY }}
          container: azure/azure-osconfig/ubuntu20.04-amd64
          mount: ${{ github.workspace }}:${{ env.MOUNT }}

      - name: Generate build
        uses: ./.github/actions/container-exec
        with:
          container: ${{ steps.container.outputs.id }}
          cmd: |
            mkdir build && cd build
            cmake --build . --target dist

      - uses: actions/upload-artifact@v2
        with:
          name: sources
          path: build/dist

  release:
    name: Release
    needs: [signing, sources]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: sources
          path: sources

      - uses: actions/download-artifact@v2
        with:
          name: ${{ needs.signing.outputs.artifact }}
          path: packages

      # TODO: need the version number/tag to properly name the release

      # TODO: get a proper changelog from the sources artifact
