name: Static analysis

on: [push, pull_request]

permissions:
  contents: read
  packages: read

jobs:
  analyze-static:
    name: Analyze Static Code
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/microsoft/kompli/ubuntu-22.04-amd64@sha256:98cd5889fffd4d86eeeeb6bd730525365e05c228a64bef2070f777abbcc59373

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        submodules: recursive
        clean: true

    - name: Prepare compile command database
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug ../src

    - name: "Temporary: install clang-tools"
      run: |
        apt-get update
        apt-get install -y clang-tools

    - name: Run clang static analyzer
      run: |
        mkdir -p output
        analyze-build-14 --verbose \
          --status-bugs \
          --exclude src/common/parson \
          --cdb build/compile_commands.json \
          --output output/scan-build

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      if: success() || failure()
      with:
        name: scan-build
        path: |
          output/scan-build
