name: Static analysis

on: [push, pull_request]

permissions:
  contents: read
  packages: read

jobs:
  analyze-static:
    name: Analyze Static Code
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/microsoft/kompli/ubuntu-22.04-amd64@sha256:98cd5889fffd4d86eeeeb6bd730525365e05c228a64bef2070f777abbcc59373

    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      with:
        submodules: recursive
        clean: true

    - name: Prepare compile command database
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug ../src

    - name: "Temporary: install clang-tools"
      run: |
        apt-get update
        apt-get install -y clang-tools

    - name: Run clang static analyzer
      run: |
        mkdir -p output
        analyze-build-14 --verbose \
          --status-bugs \
          --exclude src/adapters/pnp/azure-iot-sdk-c \
          --exclude src/adapters/pnp/PnpUtils.c \
          --exclude src/adapters/pnp/AisUtils.c \
          --exclude src/common/parson \
          --exclude src/modules/commandrunner/src/lib \
          --cdb build/compile_commands.json \
          --output output/scan-build

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      if: success() || failure()
      with:
        name: scan-build
        path: |
          output/scan-build
