name: 'Test Report'

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: unit-test
        name: Test report
        path: '*.xml'
        reporter: java-junit