name: 'Test Report'

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: unit-test-output       
        name: Unit Tests                  
        path: '*.xml'                     
        reporter: java-junit             