name: Test

on: [push]

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/check-logs
        with:
          logs: |
            ./.github/actions/checklogs/osconfig_pnp_agent.log
            ./.github/actions/checklogs/osconfig_platform.log