name: Universal NRP Test

on: [workflow_dispatch, pull_request]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/guestconfiguration-test-run.yml
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            { os: ubuntu, version: 20.04, package-type: DEB, tag: ''},
          ]
        arch: [amd64]
    with:
      target: ${{ matrix.target.os }}-${{ matrix.target.version }}
      arch: ${{ matrix.arch }}
      package-type: ${{ matrix.target.package-type }}
      tag: ${{ matrix.target.tag }}