name: Universal NRP Test

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 20 * * *' # Every day at 12pm PST (UTC-8)

jobs:
  test:
    name: Test
    uses: ./.github/workflows/universalnrp-test-run.yml
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            { os: centos, version: 8, package-type: RPM, tag: ''},
            { os: debian, version: 10, package-type: DEB, tag: ''},
            { os: debian, version: 11, package-type: DEB, tag: ''},
            { os: mariner, version: 2, package-type: RPM, tag: ''},
            { os: oraclelinux, version: 8, package-type: RPM, tag: ''},
            { os: rhel, version: 8, package-type: RPM, tag: ''},
            { os: rhel, version: 9, package-type: RPM, tag: ''},
            { os: rockylinux, version: 9, package-type: RPM, tag: ''},
            { os: sles, version: 15, package-type: RPM, tag: ''},
            { os: ubuntu, version: 20.04, package-type: DEB, tag: ''},
            { os: ubuntu, version: 22.04, package-type: DEB, tag: ''},
          ]
        policy-package:
          [
            { path: LinuxSshServerSecurityBaseline.zip, short-name: SSH, resource-count: 20 },
            { path: AzureLinuxBaseline.zip, short-name: ASB, resource-count: 168 },
          ]
        arch: [amd64]
        install-osconfig: [false]
        skip-remediation: [true, false]
    with:
      target: ${{ matrix.target.os }}-${{ matrix.target.version }}
      arch: ${{ matrix.arch }}
      package-type: ${{ matrix.target.package-type }}
      policy-package: ${{ matrix.policy-package.path }}
      policy-package-short-name: ${{ matrix.policy-package.short-name }}
      resource-count: ${{ matrix.policy-package.resource-count }}
      skip-remediation: ${{ matrix.skip-remediation }}
      install-osconfig: ${{ matrix.install-osconfig }}
      tag: ${{ matrix.target.tag }}

  # See for more details: https://github.com/marketplace/actions/publish-test-results
  report:
    name: Report
    needs: test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()
    steps:
      - name: Download Test Report Artifacts
        uses: actions/download-artifact@v4
        with:
          path: universal-nrp-test
          pattern: '*-report'
          merge-multiple: true  

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: 'universal-nrp-test/*testResults.xml'