name: Check size of a policy package
description: Checks the disk size of a policy package

inputs:
  package:
    description: the name of the package
    required: true
  limit:
    description: the maximum size of the package in kB
    required: true

runs:
  using: composite
  steps:
    - name: Check policy package size
      env:
        package: ${{ inputs.package }}
        limit: ${{ inputs.limit }}
      run: |
        failed=false

        echo "Checking the size of '$package'"
        echo "Size of '$package':"
        actual = wc -c $package | awk '{print $1}'

        if (actual > limit)
            echo "Size of '$package' of $actual kB is greater than the limit of $limit kB"
            failed=true
        else
            echo "Size of '$package' of $actual kB is at or under the limit of $limit kB"
        fi

        if [ "$failed" == true ]
        then
            echo "Check package size test failed"
            exit 1
        fi
      shell: bash
