name: Check size of a policy package
description: Checks the disk size of a policy package

inputs:
  package:
    description: the name of the package
    required: true
  limit:
    description: the maximum size of the package in kB
    required: true

runs:
  using: composite
  steps:
    - name: Check policy package size
      env:
        package: ${{ inputs.package }}
        limit: ${{ inputs.limit }}
      run: |
        failed=false

        echo "$package"
        echo "$limit"
        
        echo "Checking the size of '$package'"
        echo "Size of '$package':"

        actual=$(du -k "$package" | cut -f1)

        if [ "$actual" -gt "$limit" ]; then
            echo "Size of '$package' of $actual bytes is greater than the limit of $limit bytes"
            failed=true
        else
            echo "Size of '$package' of $actual bytes is at or under the limit of $limit bytes"
        fi

        if [ "$failed" == true ]
        then
            echo "Check package size test failed"
            exit 1
        fi
      shell: bash
